services:
  - type: web
    name: bgwipe-ai-server
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20
